src/FindBack/SiteBundle/Entity/User.php
<?php

namespace FindBack\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

class User implements AdvancedUserInterface, EquatableInterface, \Serializable
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $username;

    /**
     * @var string
     */
    private $lastname;

    /**
     * @var string
     */
    private $password;

    /**
     * @var string
     */
    private $email;

    /**
     * @var \DateTime
     */
    private $birthdate;

    /**
     * @var string
     */
    private $gender;

    /**
     * @var string
     */
    private $salt;

    /**
     * @var boolean
     */
    private $isActive;

    /**
     * @var string
     */
    protected $facebookId;

    /**
     * @var string
     */
    private $facebookPage;

    /**
     * @var \FindBack\SiteBundle\Entity\Description
     */
    private $description;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $wanteds;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $places;

    /**
     * @var string
     */
    private $website;

    /**
     * @var integer
     */
    private $found;

    /**
     * @var string
     */
    private $biography;

    public function __construct()
    {
        $this->isActive = true;
        //$this->setDescription(new \FindBack\SiteBundle\Entity\Description());
        //$this->salt = md5(uniqid(null, true));
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;
    
        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    
        return $this;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set birthdate
     *
     * @param \DateTime $birthdate
     * @return User
     */
    public function setBirthdate(\DateTime $birthdate)
    {
        $this->birthdate = $birthdate;
    
        return $this;
    }

    /**
     * @return \DateInterval
     */
    public function getAge()
    {
        if(isset($this->birthdate))
        {
            $interval = $this->birthdate->diff(new \DateTime());
            return $interval->y;
        }
        return false;
    }

    /**
     * Get birthdate
     *
     * @return \DateTime 
     */
    public function getBirthdate()
    {
        return $this->birthdate;
    }

    /**
     * Set gender
     *
     * @param string $gender
     * @return User
     */
    public function setGender($gender)
    {
        if($this->getDescription() == null) {
            $this->gender = $gender;
        }
        else {
            $this->getDescription()->setGender($gender);
        }
    
        return $this;
    }

    /**
     * Get gender
     *
     * @return string 
     */
    public function getGender()
    {
        if($this->getDescription() == null) {
            $gender = $this->gender;
        }
        else {
            $gender = $this->getDescription()->getGender();
        }
        return $gender;
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    
        return $this;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt()
    {
        //return $this->salt;
        return null;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    
        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @return array|\Symfony\Component\Security\Core\User\Role[]
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     * @param UserInterface $user
     * @return bool
     */
    public function isEqualTo(UserInterface $user)
    {
        if (!$user instanceof User) {
            return false;
        }

        if ($this->password !== $user->getPassword()) {
            return false;
        }

        if ($this->getSalt() !== $user->getSalt()) {
            return false;
        }

        if ($this->username !== $user->getUsername()) {
            return false;
        }

        return true;
    }

    public function eraseCredentials()
    {
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

    /**
     * Serializes the user.
     *
     * The serialized data have to contain the fields used by the equals method and the username.
     *
     * @return string
     */
    public function serialize()
    {
        return serialize(array(
            $this->password,
            //$this->salt,
            $this->username,
            $this->isActive,
            $this->gender,
            $this->email,
            $this->birthdate,
            $this->facebookId,
            $this->lastname,
            $this->id
        ));
    }

    /**
     * Unserializes the user.
     *
     * @param string $serialized
     */
    public function unserialize($serialized)
    {
        $data = unserialize($serialized);
        // add a few extra elements in the array to ensure that we have enough keys when unserializing
        // older data which does not include all properties.
        $data = array_merge($data, array_fill(0, 2, null));

        list(
            $this->password,
            //$this->salt,
            $this->username,
            $this->isActive,
            $this->gender,
            $this->email,
            $this->birthdate,
            $this->facebookId,
            $this->lastname,
            $this->id
            ) = $data;
    }

    /**
     * Get the full name of the user (first + last name)
     * @return string
     */
    public function getFullName()
    {
        return $this->getUsername() . ' ' . $this->getLastname();
    }

    /**
     * @param string $facebookId
     * @return void
     */
    public function setFacebookId($facebookId)
    {
        $this->facebookId = $facebookId;
        $this->setUsername($facebookId);
    }

    /**
     * @return string
     */
    public function getFacebookId()
    {
        return $this->facebookId;
    }

    /**
     * @param Array
     */
    public function setFBData($fbdata)
    {
        if (isset($fbdata['id'])) {
            $this->setFacebookId($fbdata['id']);
        }
        if (isset($fbdata['first_name'])) {
            $this->setUsername($fbdata['first_name']);
        }
        if (isset($fbdata['last_name'])) {
            $this->setLastname($fbdata['last_name']);
        }
        if (isset($fbdata['gender'])) {
            $this->setGender($fbdata['gender']);
        }
        if (isset($fbdata['birthday'])) {
            $birthdate = new \DateTime($fbdata['birthday']);
            $this->setBirthdate($birthdate);
        }
        if (isset($fbdata['link'])) {
            $this->setFacebookPage($fbdata['link']);
        }
    }

    /**
     * Set facebookPage
     *
     * @param string $facebookPage
     * @return User
     */
    public function setFacebookPage($facebookPage)
    {
        $this->facebookPage = $facebookPage;
    
        return $this;
    }

    /**
     * Get facebookPage
     *
     * @return string 
     */
    public function getFacebookPage()
    {
        return $this->facebookPage;
    }

    /**
     * Set description
     *
     * @param \FindBack\SiteBundle\Entity\Description $description
     * @return User
     */
    public function setDescription(\FindBack\SiteBundle\Entity\Description $description = null)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return \FindBack\SiteBundle\Entity\Description 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add wanteds
     *
     * @param \FindBack\SiteBundle\Entity\Wanted $wanteds
     * @return User
     */
    public function addWanted(\FindBack\SiteBundle\Entity\Wanted $wanteds)
    {
        $this->wanteds[] = $wanteds;
    
        return $this;
    }

    /**
     * Remove wanteds
     *

src/FindBack/SiteBundle/Controller/UserController.php
<?php

namespace FindBack\SiteBundle\Controller;

use FindBack\SiteBundle\Entity\Description;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\Security\Core\User;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use FindBack\SiteBundle\Form\Type\UserEditType;

class UserController extends Controller
{
    public function indexAction()
    {
        /** @var \FindBack\SiteBundle\Entity\User $user */
        $user = $this->get('security.context')->getToken()->getUser();
        $descriptionRepo = $this->getDoctrine()->getManager()->getRepository('FindBack\SiteBundle\Entity\Description');
        $description = $descriptionRepo->findOneBy(array('user' => $user->getId()));

        $wantedRepo = $this->getDoctrine()->getManager()->getRepository('FindBack\SiteBundle\Entity\Wanted');
        $wanteds = $wantedRepo->findBy(array('user' => $user->getId()));

        return $this->render('FindBackSiteBundle:User:index.html.twig', array(
            'user' => $user,
            'wanteds' => $wanteds,
            'description' => $description
        ));
    }

    public function editAction(Request $request)
    {
        /** @var \FindBack\SiteBundle\Entity\User $user */
        $user = $this->get('security.context')->getToken()->getUser();
        $descriptionRepo = $this->getDoctrine()->getManager()->getRepository('FindBack\SiteBundle\Entity\Description');
        $description = $descriptionRepo->findOneBy(array('user' => $user->getId()));

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(new UserEditType(), $user);
        $form->handleRequest($request);

        if ($request->getMethod() == 'POST') {
            if ($form->isValid()) {

                $desc = $user->getDescription();
                $desc->setUser($user);
                $em->persist($desc);
                $user->setDescription($desc);

                $em->persist($user);
                $em->flush();

                $this->get('session')->getFlashBag()->add(
                    'notice',
                    'Modifications enregistrées !'
                );

                return $this->redirect($this->generateUrl('account'));
            }
        }

        return $this->render('FindBackSiteBundle:User:edit.html.twig', array(
            'form' => $form->createView(),
            'user' => $user,
            'description' => $description
        ));
    }
}

src/FindBack/SiteBundle/Resources/views/User/edit.html.twig
{% extends "FindBackSiteBundle::layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <style type="text/css">
        .infos {
            position: relative;
            float: left;
        }
        .well.extended, .well.extended > div {
            width: auto;
            display: block;
            clear: both;
        }
        .well {
            width: 275px;
        }
        .identity, .sub-identity, label {
            width: 120px;
            font-weight: bold;
            display: inline-block;
            margin-right: 10px;
        }
        input[type="submit"] {
            width: 200px;
        }
        input[name*="user["] {
            width: 130px;
            height: 10px;
            margin-bottom: 5px;
            font-size: 10px;
        }
        form div {
            display: inline-block;
        }
        select[name*="user["] {
            width: 130px;
            height: 20px;
            font-size: 10px;
            margin-bottom: 5px;
            padding: 0;
        }
        textarea {
            min-height: 100px;
        }
    </style>
{% endblock %}

{% block left_title %}
    <h5><i class="icon-user"></i> Mon compte</h5>
{% endblock %}
{% block left_content %}
    <form id="user_form" action="{{ path('account_edit') }}" method="post" {{ form_enctype(form) }}>
    <div class="infos">
        <h5>Informations personnelles</h5>
        <ul class="well">
            <li><span class="identity">Nom</span>{{ user.username }} {{ user.lastname }}</li>
            <li><span class="identity">Âge</span>{{ user.getAge }} ans</li>
            <li><span class="identity">Recherches</span>{{ user.nbWanteds }}</li>
            <li><span class="identity">Retrouvailles</span>{{ user.found }}</li>
            <li><span class="identity">Email <i class="icon-eye-close"></i></span>{{ form_row(form.email) }}</li>
            <li><span class="identity">Profil Facebook</span>{{ form_row(form.facebookPage) }}</li>
            <li><span class="identity">Site Web</span>{{ form_row(form.website) }}</li>
        </ul>
    </div>
    <div class="infos" style="float:right;">
        <h5>Description physique</h5>
        <ul class="well">
            <li>{{ form_row(form.description.gender) }}</li>
            <li>{{ form_row(form.description.height) }}</li>
            <li>{{ form_row(form.description.type) }}</li>
            <li>{{ form_row(form.description.hairColor) }}</li>
            <li>{{ form_row(form.description.hairCut) }}</li>
            <li>{{ form_row(form.description.eyes) }}</li>
            <li>{{ form_row(form.description.piercing) }}</li>
            <li>{{ form_row(form.description.tattoo) }}</li>
        </ul>
    </div>
    <h5>Lieux fréquentés</h5>
    <div class="well extended">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#places" data-toggle="tab">Lieux</a></li>
            <li><a href="#carte" data-toggle="tab">Carte</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="places">
                <ul>
                    <li>Aix-en-Provence > Rue de la verrerie > Bar/Discothèque, Le Scat</li>
                </ul>
            </div>
            <div class="tab-pane" id="carte">
                <div id="map" style="height: 400px; width: 100%;"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block right_title %}
    <h5><i class="icon-edit"></i> Mettre à jour</h5>
{% endblock %}

{% block right_content %}
    <div align="center">
        <p><input type="submit" class="btn btn-success"  value="Terminer" /></p>
        <p><a href="{{ path('account') }}" class="btn btn-danger" style="width: 175px;">Annuler</a></p>
    </div>
{% endblock %}

{% block right_content2 %}
    <h5>Bio</h5>
    <div align="center" style="padding: 10px">
        <div class="profile_img">
            <img src="https://graph.facebook.com/{{ user.facebookId }}/picture?width=160&height=160" />
        </div>
        <div class="well" style="margin: 10px; width: auto;">
            {{ form_row(form.biography) }}
        </div>
    </div>
        {{ form_widget(form._token) }}
    </form>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD4QDBP3GO6fXiHJGSLweZwPpbaMf1FSJw&sensor=false"></script>
    <script type="text/javascript">
        $('ul.nav.nav-tabs li a[data-toggle="tab"]').click(function() {
            setTimeout(function() {
                var latlng = new google.maps.LatLng(46.70973594407157, 2.61474609375);
                var map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 5,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });

                google.maps.event.addListener(map, 'click', function(e) {
                    alert(e.latLng);
                });

                // Ceci ds une boucle qui liste les lieux

                var marker = new google.maps.Marker({
                    position: latlng,
                    map: map,
                    title: "Property location"
                });

                google.maps.event.addListener(marker, 'click', function() {
                    var infowindow = new google.maps.InfoWindow({
                        content: marker.title
                    });
                    infowindow.open(marker.get('map'), marker);
                });

            }, 500);
        });
    </script>
{% endblock %}

src/FindBack/SiteBundle/Resources/views/User/index.html.twig
{% extends "FindBackSiteBundle::layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <style type="text/css">
        .infos {
            position: relative;
            float: left;
        }
        .well {
            width: 275px;
        }
        .well.extended {
            width: auto;
        }
        .identity, .sub-identity {
            width: 120px;
            font-weight: bold;
            display: inline-block;
            margin-right: 10px;
        }
        .sub-identity {
            margin-left: 10px;
            width: 110px;
        }
    </style>
{% endblock %}

{% block left_title %}
    <h5><i class="icon-user"></i> Mon compte</h5>
{% endblock %}
{% block left_content %}
    <div class="alert alert-info hide">
        Les informations suivies du sigle <i class="icon-eye-close"></i> ne sont pas visibles par autrui.<br />
        Pour visualiser de quelle manière un utilisateur lambda voit votre profil, cliquez sur le bouton associé dans l'espace de droite.
    </div>
    <div class="infos">
        <h5>Informations personnelles</h5>
        <ul class="well">
            <li><span class="identity">Nom</span>{{ user.username }} {{ user.lastname }}</li>
            <li><span class="identity">Âge</span>{{ user.age }} ans</li>
            <li><span class="identity">Recherches</span>{{ user.nbWanteds }}</li>
            <li><span class="identity">Retrouvailles</span>{{ user.found }}</li>
            <li><span class="identity">Email <i class="icon-eye-close"></i></span><a href="mailto:{{ user.email }}">{{ user.email }}</a></li>
            {% if user.facebookPage %}
                <li><span class="identity">Facebook</span><a href="{{ user.facebookPage }}" target="_blank">Profil</a></li>
            {% endif %}
            {% if user.website %}
                <li><span class="identity">Site Web</span><a href="http://{{ user.website }}" target="_blank">{{ user.website }}</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="infos" style="float:right;">
        <h5>Description physique</h5>
        <ul class="well">
            {% if description %}
            <li><span class="identity">Sexe</span>{{ user.gender|trans }}</li>
            <li><span class="identity">Taille</span>{{ description.height }}</li>
            <li><span class="identity">Type</span>{{ description.type }}</li>
            <li><span class="identity">Cheveux</span>{{ description.hairColor }}</li>
            <li><span class="identity">Coupe</span>{{ description.hairCut }}</li>
            <li><span class="identity">Yeux</span>{{ description.eyes }}</li>
            <li><span class="identity">Piercing</span>{{ description.piercing }}</li>
            <li><span class="identity">Tatouage</span>{{ description.tattoo }}</li>
            {% else %}
                <li style="text-align: center;"><a href="#" class="btn btn-success">Ajouter des détails</a></li>
            {% endif %}
        </ul>
    </div>
    <h5 style="clear:both;">Lieux fréquentés <a href="#modal" role="button" data-toggle="modal"><i class="icon-question-sign"></i></a></h5>
    <div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="modalLabel">Lieux fréquentés</h3>
        </div>
        <div class="modal-body">
            <p>Vous devez spécifier des lieux que vous fréquentez de manière <b>régulière</b> en sortie.</p>
            <p><b>Rassurez-vous</b>, le but n'est pas de vous espionner mais d'obtenir des données précises sur les lieux que vous fréquentez en sortie et dans lesquels il est possible que <strong>quelqu'un vous recherche</strong>.</p>
            <p>Grâce à ces données, nous vous mettrons <strong>en relation</strong> avec des personnes qui <strong>recherchent</strong> un <b>profil similaire au vôtre</b> dans les lieux renseignés.</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
        </div>
    </div>
    {# tabs avec formulaire et map #}
    <div class="well extended">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#places" data-toggle="tab">Lieux</a></li>
            <li><a href="#carte" data-toggle="tab">Carte</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="places">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Ville</th>
                            <th>Adresse</th>
                            <th>Nom</th>
                            <th>Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Aix-en-Provence</td>
                            <td>Rue de la verrerie</td>
                            <td>Le Scat</td>
                            <td>Bar / Discothèque</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="carte">
                <div id="map" style="height: 400px; width: 100%;"></div>
            </div>
        </div>
    </div>

    <h5>Mes avis de recherche</h5>
    <div class="well extended">
        {% if wanteds %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Sexe</th>
                    <th>Ville</th>
                    <th>Établissement</th>
                    <th>Date</th>
                    <th>Heure</th>
                </tr>
            </thead>
            <tbody>
                {% for wanted in wanteds %}
                    <tr>
                        <td>{{ wanted.description.gender }}</td>
                        <td>{{ wanted.place.city }}</td>
                        <td>{{ wanted.place.establishmentName }}</td>
                        <td>{{ wanted.date.date }}</td>
                        <td>{{ wanted.date.time }}</td>
                        <td><a href="{{ path('wanted_show', { 'id': wanted.id }) }}"><i class="icon-search"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p style="margin: 0;"><i>Aucun avis de recherche.</i></p>
        {% endif %}
    </div>

    <h5>Personnes retrouvées</h5>
    <div class="well" style="width:325px">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Statut</th>
                </tr>
            </thead>
            <tbody>
                <tr class="success">
                    <td><a href="#">Giulia Belgada</a></td>
                    <td>Confirmé <i class="icon-ok"></i></td>
                </tr>
                <tr class="info">
                    <td><a href="#">Bar Refaeli</a></td>
                    <td>En attente de confirmation... <i class="icon-time"></i></td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block right_title %}
    <h5><i class="icon-edit"></i> Mettre à jour</h5>
{% endblock %}

{% block right_content %}
    <div align="center">
        <p><a class="btn" href="{{ path('account_edit') }}" style="width: 175px;">Éditer mes informations</a></p>
        <p><a class="btn btn-primary" href="#" style="width: 175px;">Voir mon profil public</a></p>
    </div>
{% endblock %}

{% block right_content2 %}
    <h5>Bio</h5>
    <div align="center" style="padding: 10px">
        <div class="profile_img">
            {% if user.facebookId %}
                <img src="https://graph.facebook.com/{{ user.facebookId }}/picture?width=160&height=160" />
            {% else %}
                <p>Pour afficher votre photo, vous devez lier votre compte à Facebook !<br />
                Faites-le en ajoutant le lien de votre mur facebook lorsque vous éditez vos informations.
                </p>
            {% endif %}
        </div>
        <p class="well" style="margin: 10px; width: auto;text-align: left;">
            {{ user.biography|nl2br }}
        </p>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD4QDBP3GO6fXiHJGSLweZwPpbaMf1FSJw&sensor=false"></script>
    <script type="text/javascript">
        $('.identity > .icon-eye-close').click(function() {
            $('.alert.alert-info.hide').toggle('slow');
        });
        $('ul.nav.nav-tabs li a[data-toggle="tab"]').click(function() {
            setTimeout(function() {
                var latlng = new google.maps.LatLng(46.70973594407157, 2.61474609375);
                var map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 5,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });

                google.maps.event.addListener(map, 'click', function(e) {
                    alert(e.latLng);
                });

                // Ceci ds une boucle qui liste les lieux
                // Il faut récupérer les lieux et plus exactement leur "location" ds la bdd
                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng(43.52935348728217, 5.447099804878235), //latlng,
                    map: map,
                    title: "Property location"
                });

                google.maps.event.addListener(marker, 'click', function() {
                    var infowindow = new google.maps.InfoWindow({
                        content: marker.title
                    });
                    infowindow.open(marker.get('map'), marker);
                });

            }, 500);
        });
    </script>
{% endblock %}